[package]
name = "dos_sql"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = [
    "runtime-tokio-native-tls", 
    "postgres", 
    "time", 
    "json", 
    "macros"
]}
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
time = { version = "0.3", features = ["serde"] }
